### ISSUE TITLE
Plot display on PC

### ISSUE THREAD

**Issue by Yashkincot** [CIRDLES/Tripoli#235]
Tripoli Version: 0.5.1
Java Version: 21.0.3
JavaFX Version: 21.0.3+1
OS: Windows 10 10.0

Issue details:
On a PC, the bars don't go over the xs in the reported statistics for the plots.  The red line for the mean extends beyond the left plot boundary. The block labels are not centered on the blocks on the x-axis.

![ScreenCapTripoli](https://github.com/CIRDLES/Tripoli/assets/130931450/3966c019-1944-4f62-9cd4-cde6fd4f6cf0)

**Comment by bowring** [comment]
@Yashkincot - thanks for your thoughtful comments. The bar issue on windows is a font problem and the solution may be using a different font on windows.  The red line is by design to draw the user's attention - do you think it should protrude at all?  The block labels were designed to be left justified to denote the start of each block - do you think they need to be centered?
Cheers

**Comment by joneelzinto** [comment]
Hey Jim, centering the block labels will be great, and truncating the red line at left plot boundary will also look better. 

Cheers.
